{{- if and (eq .Values.profile "starter") .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "soha-observability.fullname" . }}-loki
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "soha-observability.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{- end }}
