{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soha-observability.serviceAccountName" . }}
  labels:
    {{- include "soha-observability.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
