apiVersion: v2
name: soha-agent
description: OpenSoha cluster agent for remote Kubernetes operations.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/opensoha/soha-agent
sources:
  - https://github.com/opensoha/soha-agent
maintainers:
  - name: OpenSoha
    url: https://github.com/opensoha
keywords:
  - opensoha
  - soha-agent
  - kubernetes
  - delivery
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/opensoha/soha-agent
