apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soha-agent.fullname" . }}-secrets
  labels:
    {{- include "soha-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  agent-bearer-token: {{ .Values.secrets.agentBearerToken | quote }}
  control-plane-bearer-token: {{ .Values.secrets.controlPlaneBearerToken | quote }}
