apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soha.fullname" . }}-config
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "soha.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ include "soha.postgresPassword" . | quote }}
  execution-runner-token: {{ .Values.config.runtime.executionRunnerToken | quote }}
  config.yaml: |-
{{- include "soha.appConfig" . | nindent 4 }}
